### ISSUE TITLE
Scheduler cannot recover running jobs

### ISSUE THREAD

**Issue by warownia1** [warownia1/Slivka#52]
Scheduler can't recover running jobs because ``run_configuration`` is ``None``.
``run_configuration`` field of ``slivka.db.models.Request`` is not set when the job is created. When the requested job is picked-up for execution and the proper configuration is selected and the runner is created, the scheduler should save configuration name-id to the database.

```
Traceback (most recent call last):
...
  File "/cluster/rs_lab/mmwarowny/miniconda3/envs/slivka/lib/python3.5/site-packages/Slivka-0.3a4-py3.5.egg/slivka/command.py", line 167, in scheduler
    scheduler = Scheduler()
  File "/cluster/rs_lab/mmwarowny/miniconda3/envs/slivka/lib/python3.5/site-packages/Slivka-0.3a4-py3.5.egg/slivka/scheduler/scheduler.py", line 46, in __init__
    self._restore_jobs()
  File "/cluster/rs_lab/mmwarowny/miniconda3/envs/slivka/lib/python3.5/site-packages/Slivka-0.3a4-py3.5.egg/slivka/scheduler/scheduler.py", line 88, in _restore_jobs
    .get_runner_class(request.run_configuration)
  File "/cluster/rs_lab/mmwarowny/miniconda3/envs/slivka/lib/python3.5/site-packages/Slivka-0.3a4-py3.5.egg/slivka/scheduler/execution_manager.py", line 92, in get_runner_class
    return self.configurations[name].runner
KeyError: None
```

**Comment by warownia1** [comment]
Inserting run configuration values to the database by allows restoring running jobs.
